# Limpieza de datos

La limpieza de datos es el proceso de encontrar y corregir los datos  inexistentes o incorrectos presentes en el conjunto d edatos. Para la limpieza de datos se puede usar la libreria de código abierto Pandas.

La limpieza de datos es importante ya que
los conjuntos de datos tendrán valores faltantes por distintas razones, por lo que es necesario saber tratar con ellos.

Es la practica de corregir o eliminar datos inexactos, dañados, mal formateados, duplicados o incompletos de un conjunto de datos.

## Datos faltantes


Ocurre cuando falata información disponible para una o más columnas o para caracteristicas de las filas.

Los datos faltantes son datos que:

    - No se recoliparon, aunque existan
    - Datos que nunca existieron

Ej. Encuesta sobre los intereses de usuarios

    -  Información faltante sobre los ingresos mensuales

### Qué son sol datos falyantes

Los datos faltantes son: 

    - Observaciones que no se registraron
    - Datos corruptos (Corrupción de datos)


En pandas los datos faltantes se representan de dos formas:

    - None: objeto único de Python que se usa para datos faltantes
    - NaN: (Not a Number) Valor especial de punto flotante reconocido por todos los sistemas utilizan la representación estándar de IEEE.

####  Importancia del manejo de datos faltanes

Sumanejo es impoetnate, ya que muchos algoritmos de aprendizaje automático no los admite, por lo que es necesario hacer una limpeza de los datos, para lograrlo, debemos:

    - Revisar los valores nulos dentro de las columnas
    - Revisar las filas que puedan tener muchos valores faltantes.

#### Dataframe

El dataframe (empleados.csv), contiene la información de los colaboradores (empledos), de una organización o empresa, etc, la información del dataframe (df) es el siguiente:

    - Filas que contiene mchos valores nulos
    - NaN o none

#### Eliminaciónde columnas

Es importante recordar que solo se deben eliminar datos en las columnas cuando tengan muchos valores nulos.

#### Eliminación de filas

Una de las formas de tratar con los datos faltantes es eliminar las columnas.

### ¿Cómo tratar con los datos faltantes?

Una de las formas de tratar con los datos faltantes es eliminar las columnas.

#### Código | Desafios

##### Desafío

Hay columnas en nuestro dataframe  que tiene valores Nan o None, tu tarea es calcular el número de valores faltantes para cada columna.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/empleados.csv', delimiter=";")

In [5]:
df.head()

,Nombre,Apellido,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,NaN,Masculino,Soltero(a),22.0,3.0,2423.0,No,Publicidad
1,Carlos,NaN,Masculino,Casado(a),38.0,10.0,3132.0,Sí,NaN
2,Felipa,NaN,Femenino,Soltero(a),26.0,5.0,2639.0,No,Comercial
3,Daniel,NaN,Masculino,Casado(a),35.0,10.0,3122.0,No,Comercial
4,John,NaN,Masculino,Casado(a),35.0,13.0,3431.0,Sí,Servicios al cliente

In [4]:
df.shape

(251, 9)

In [5]:
df.isnull().sum()

Nombre            6
Apellido        251
Sexo             37
Estado_Civil      4
Edad             61
Experiencia       4
Salario           6
Gerencia         21
Departamento     12
dtype: int64

In [6]:
df.notnull().sum()

Nombre          245
Apellido          0
Sexo            214
Estado_Civil    247
Edad            190
Experiencia     247
Salario         245
Gerencia        230
Departamento    239
dtype: int64

#### Código | Eliminación  columnas y filas

##### Desafio | Eliminar columnas

In [7]:
#### eliminar columnas (axis=1) con valores nulos

df_drop_columns = df.drop(axis=1, labels=['Apellido'])
df_drop_columns.shape

(251, 8)

##### Desafio | Eliminar filas

El desafio es encontrar y eliminar las columnas que contienen valores nulos dentro del dataframe.

In [8]:
# Eliminar filas
# Identificación de filas con datos nulos
df_drop_columns[df_drop_columns.isnull().any(axis=1)]

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
1,Carlos,Masculino,Casado(a),38.0,10.0,3132.0,Sí,NaN
5,Edward,Masculino,Soltero(a),NaN,NaN,4500.0,No,Legal
7,Amaya,Femenino,Divorciado(a),22.0,3.0,2450.0,NaN,Comercial
10,Febe,Femenino,Casado(a),44.0,22.0,4359.0,No,NaN
15,NaN,Femenino,NaN,44.0,22.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
241,Robert,NaN,Soltero(a),33.0,11.0,3267.0,No,Recursos Humanos
242,Kevin,NaN,Divorciado(a),NaN,20.0,4166.0,No,Finanzas
243,Amaro,Masculino,Casado(a),NaN,24.0,4510.0,No,Comercial
248,Eric,NaN,Casado(a),25.0,7.0,2880.0,Sí,Recursos Humanos
249,Marc,NaN,Casado(a),24.0,2.0,2172.0,No,Producto

In [9]:
# Eliminación de filas con datos nulos (axis=0)
df_dropna = df_drop_columns.dropna(axis=0)
df_dropna.shape

(145, 8)

In [10]:
### Verificación de filas sin datos nulos
df_dropna[df_dropna.isnull().any(axis=1)]

Empty DataFrame
Columns: [Nombre, Sexo, Estado_Civil, Edad, Experiencia, Salario, Gerencia, Departamento]
Index: []

### Registros duplicados

Debemos hacernos las siguientes preguntas:

    - ¿Tenemos datos faltantes?
    - ¿Sabemos cómo tratarlos?

Es importante eliminar los datos duplicados por las siguientes causas:

    - Ocupan espacio de almacenamiendo innecesarios
    - Relentizan los calculos al mínimo
    - Sesan los resultados del análisis
    - Ponen en riezgo  la integridad de los datos

#### Código | Desafío

##### Desafío | Datos duplicados

In [11]:
#### Identificación de valores duplicados
df_dropna[df_dropna.duplicated()]

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
14,Selena,Femenino,Casado(a),24.0,6.0,2709.0,Sí,Contabilidad
65,Lucio,Masculino,Soltero(a),54.0,12.0,3317.0,No,Recursos Humanos

In [12]:
### Eliminación de valores duplicados
df_drop_duplicates = df_dropna.drop_duplicates()
df_drop_duplicates.head()

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,Masculino,Soltero(a),22.0,3.0,2423.0,No,Publicidad
2,Felipa,Femenino,Soltero(a),26.0,5.0,2639.0,No,Comercial
3,Daniel,Masculino,Casado(a),35.0,10.0,3122.0,No,Comercial
4,John,Masculino,Casado(a),35.0,13.0,3431.0,Sí,Servicios al cliente
6,Ruperta,Femenino,Casado(a),54.0,18.0,3962.0,No,Producto

In [13]:
### Verificación de datos duplicados eliminados
df_drop_duplicates[df_drop_duplicates.duplicated()]

Empty DataFrame
Columns: [Nombre, Sexo, Estado_Civil, Edad, Experiencia, Salario, Gerencia, Departamento]
Index: []

#### Rellenar los datos faltantes (imputación)

A veces los valores numéricos vienen incompletos, ya sea como NaN o None, cuando es el caso, podemos relizar la técnica llamada **imputación**, que no spermite cambiar lo svalores faltantes con valores sencibles.

#### Código | Desafío

Rellevar los datos faltantes de la columna edad con la media de la edad.

##### Desafío | Imputación de datos

In [14]:
### Rellenar valores nulos con un valor específico
#### Detectar los datos nulos
df_drop_columns.isnull().sum()

Nombre           6
Sexo            37
Estado_Civil     4
Edad            61
Experiencia      4
Salario          6
Gerencia        21
Departamento    12
dtype: int64

In [20]:
##### Eliminamos datos nulos de columnas con datos te tipo string
df_dropna_str_columns = df_drop_columns.dropna(subset=['Nombre', 'Sexo',  'Estado_Civil', 'Gerencia', 'Departamento'])
df_dropna_str_columns.isnull().sum()

Nombre           0
Sexo             0
Estado_Civil     0
Edad            48
Experiencia      1
Salario          2
Gerencia         0
Departamento     0
dtype: int64

In [22]:
##### Imputación de datos nulos en columnas con datos de tipo numericos (int, float)
# 1. Definimos las columnas numéricas que queremos cambiar
columnas_num = ['Edad', 'Experiencia', 'Salario']

df_dropna_num_columns = df_dropna_str_columns.dropna(subset=columnas_num)
df_dropna_num_columns.head()

,Nombre,Sexo,Estado_Civil,Edad,Experiencia,Salario,Gerencia,Departamento
0,Alexandro,Masculino,Soltero(a),22.0,3.0,2423.0,No,Publicidad
2,Felipa,Femenino,Soltero(a),26.0,5.0,2639.0,No,Comercial
3,Daniel,Masculino,Casado(a),35.0,10.0,3122.0,No,Comercial
4,John,Masculino,Casado(a),35.0,13.0,3431.0,Sí,Servicios al cliente
6,Ruperta,Femenino,Casado(a),54.0,18.0,3962.0,No,Producto

In [23]:
# 3. Calculamos la media y rellenamos solo en esas columnas
dropna_num_columns = df_drop_columns[columnas_num]
df_dropna_num_columns[columnas_num] = df_dropna_num_columns[columnas_num].fillna(df_dropna_num_columns[columnas_num].mean())

###### Comprobación de la imputación de datos nulos en columnas con datos de tipo numericos (int, float)
df_dropna_num_columns.isnull().sum()

Nombre          0
Sexo            0
Estado_Civil    0
Edad            0
Experiencia     0
Salario         0
Gerencia        0
Departamento    0
dtype: int64